## used by ConfigurationProperties
my:
  servers:
    - 192.168.0.1
    - 192.168.0.2
    - 192.168.0.3

## global
spring:
  profiles:
    active: dev
    include: dev, demo
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
debug: true
logging:
  level: debug
  file: app.log

--- ## dev env

spring:
  profiles: dev


--- ## demo env
spring:
  profiles: demo