/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class biz_llmall_JavaCallC */

#ifndef _Included_biz_llmall_JavaCallC
#define _Included_biz_llmall_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     biz_llmall_JavaCallC
 * Method:    hellC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_biz_llmall_JavaCallC_hellC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
